Select
    ranking,
    annee,
    cast(round(avg(avg_age),2) as float64) as avg_age,
    cast(round(avg(avg_market_value),2) as float64) as avg_market_value,
    cast(round(avg(avg_note),2) as float64) as avg_note,
    cast(round(avg(avg_total_point),2) as float64) as avg_total_point,
    cast(round(avg(games_played),2) as float64) as games_played,
    cast(round(avg(win),2) as float64) as win,
    cast(round(avg(draw),2) as integer) as draw,
    cast(round(avg(loss),2) as float64) as loss,
 #   cast(round(avg(goals_for),2) as float64) as goals_for,
 #   cast(round(avg(goals_again),2) as float64) as goals_again,
 #   cast(round(avg(goal_difference),2) as float64) as goal_difference,
    cast(round(avg(avg_goals_for_by_match),2) as float64) as avg_goals_for_pg ,
    cast(round(avg(avg_goals_again_by_match),2) as float64) as avg_goals_again_pg,
    cast(round(avg(avg_goals_for_by_match-avg_goals_again_by_match),2) as float64) as avg_goals_diff_pg ,
    cast(round(avg(win_rate),2) as float64) as avg_win_rate ,
    cast(round(avg(penalty_pg), 2) as float64) as avg_penalty,
    cast(round(avg(own_goal_pg), 2) as float64) as avg_own_goal,
    cast(round(avg(shots_pg), 2) as float64) as avg_shots_pg,
    cast(round(avg(discipline), 2) as float64) as avg_discipline,
    cast(round(avg(aerials_won_pg), 2) as float64) as avg_aerials_won_pg,
    cast(round(avg(pass_pg), 2) as float64) as avg_pass_pg,
    cast(round(avg(open_play_pg), 2) as float64) as avg_open_play_pg,
    cast(round(avg(interceptions_pg), 2) as float64) as avg_interceptions_pg,
    cast(round(avg(fouls_pg), 2) as float64) as avg_fouls_pg,
    cast(round(avg(offsides_pg), 2) as float64) as avg_offsides_pg,
    cast(round(avg(possession), 2) as float64) as avg_possession,
    cast(round(avg(total_team_goals), 2) as float64) as avg_total_team_goals,
    cast(round(avg(total_team_caps), 2) as float64) as avg_total_team_caps,
    cast(round(avg(classement_fifa), 2) as float64) as avg_classement_fifa,
from {{ref('wiki_scrap_enriched_2018_22_stats')}}
where annee > 2014 
GROUP by ranking, annee