version: 2

sources:
  - name: raw_dataset #The name you want to give to the dataset
    schema: raw_dataset #schema is the name of the dataset in BigQuery
    description: Temps de jeu des joueurs
    tables:
      - name: appearances #name you want to give the table
        identifier: appearances #identifier is the name of the table in BigQuery
        columns:
          - name: appearance_id
          - name: game_id
          - name: player_id
          - name: player_club_id
          - name: player_current_club_id
          - name: date
          - name : player_name
          - name : competition_id
          - name : yellow_cards
          - name : red_cards
          - name : goals
          - name : assists
          - name : minutes_played
      - name: clubs #name you want to give the table
        identifier: clubs #identifier is the name of the table in BigQuery
        columns:
          - name: club_id
          - name: club_code
          - name: name
          - name: domestic_competition_id
          - name: total_market_value
          - name: squad_size
          - name : average_age
          - name : foreigners_number
          - name : foreigners_percentage
          - name : national_team_players
          - name : stadium_name
          - name : stadium_seats
          - name : net_transfer_record
          - name : coach_name
          - name : last_season
          - name : filename
          - name : url
      - name: player_valuations #name you want to give the table
        identifier: player_valuations #identifier is the name of the table in BigQuery
        columns:
          - name: fullname
          - name: player_id
          - name: date
          - name: market_value_in_eur
          - name: current_club_id
          - name: player_club_domestic_competition_id
      - name: players #name you want to give the table
        identifier: players #identifier is the name of the table in BigQuery
        columns:
          - name: fullname
          - name: player_id
          - name: first_name
          - name: last_name
          - name: name
          - name: last_season
          - name: current_club_id
          - name: player_code
          - name: country_of_birth
          - name: city_of_birth
          - name: country_of_citizenship
          - name: date_of_birth
          - name: sub_position
          - name: foot
          - name: height_in_cm
          - name: contract_expiration_date
          - name: agent_name
          - name: image_url
          - name: url
          - name: current_club_domestic_competition_id
          - name: current_club_name
          - name: market_value_in_eur
          - name: highest_market_value_in_eur
      - name: combined_world_cup_data #name you want to give the table
        identifier: combined_world_cup_data #identifier is the name of the table in BigQuery
        columns:
          - name: date_date
          - name: position
          - name: team
          - name: country_id
          - name: games_played
          - name: win
          - name: draw
          - name: loss
          - name: goals_for
          - name: goals_again
          - name: goal_difference
          - name: points
      - name: wiki_scrapp_country_cdm #name you want to give the table
        identifier: wiki_scrapp_country_cdm #identifier is the name of the table in BigQuery
        columns:
          - name: name
          - name: poste
          - name: pays_fr
          - name: pays_en
          - name: an
          - name: win
          - name: Jour
          - name: Mois
          - name: Annee
          - name: Age
          - name: country_id
      - name: competitions #name you want to give the table
        identifier: competitions #identifier is the name of the table in BigQuery
        columns:
          - name: competition_id
          - name: competition_code
          - name: name
          - name: sub_type
          - name: type
          - name: country_id
          - name: country_name
          - name: domestic_league_code
          - name: confederation
          - name: url
          - name: is_major_national_league
      - name: sofifa_clean #name you want to give the table
        identifier: sofifa_clean #identifier is the name of the table in BigQuery
        columns:
          - name: Club_nat
          - name: Nom
          - name: Age
          - name: Position
          - name: Note
          - name: Potential
          - name: Team
          - name: Prefered_pos
          - name: Value
          - name: Salaire
          - name: Total_Point
          - name: Prenom
          - name: Taille_fr
          - name: Taille_en
          - name: Poids_kg
          - name: Poids_lbs
          - name: Player_id
      - name: world_cup_2022_consolide # Add your new table here
        identifier: world_cup_2022_consolide # The identifier is the name of the table in BigQuery
        columns:
          - name: annee
          - name: position_finale
          - name: ranking
          - name: team
          - name: left_side
          - name: middle_of_the_pitch
          - name: right_side
          - name: cross_pg
          - name: through_ball_pg
          - name: long_balls_pg
          - name: short_passes_pg
          - name: open_play
          - name: counter_attack
          - name: set_piece
          - name: penalty
          - name: own_goal
          - name: goals
          - name: shots_pg
          - name: discipline
          - name: possession
          - name: pass
          - name: aerials_won
          - name: rating
          - name: shots_pg_def
          - name: tackles_pg
          - name: interceptions_pg
          - name: fouls_pg
          - name: offsides_pg
          - name: games_played
      - name: world_cup_2018_consolide # Add your new table here
        identifier: world_cup_2018_consolide # The identifier is the name of the table in BigQuery
        columns:
          - name: annee
          - name: position_finale
          - name: ranking
          - name: team
          - name: left_side
          - name: middle_of_the_pitch
          - name: right_side
          - name: cross_pg
          - name: through_ball_pg
          - name: long_balls_pg
          - name: short_passes_pg
          - name: open_play
          - name: counter_attack
          - name: set_piece
          - name: penalty
          - name: own_goal
          - name: goals
          - name: shots_pg
          - name: discipline
          - name: possession
          - name: pass
          - name: aerials_won
          - name: rating
          - name: shots_pg_def
          - name: tackles_pg
          - name: interceptions_pg
          - name: fouls_pg
          - name: offsides_pg
          - name: games_played
